# Generated by Django 4.2.1 on 2024-03-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product',
        ),
    ]
