# Generated by Django 4.2.1 on 2024-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_contact_alter_checkout_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default='-121212'),
        ),
    ]
